### PR TITLE
Showing a dot when Tally is off

### PR DESCRIPTION
**Pull request by thomasvoorend**
This prevents confusion whether the tally has power or not.

### CODE REVIEW

**Comment by thomasvoorend** [comment]
Hopefully this is a nice to have feature for the code :)

Kind regards,
Thomas Voorend

**Comment by ThomasMout** [comment]
Hi Thomas,

Great idea! I've always thought about adding this but never did. 
I'm going to change your code a bit for consistency and to remove a few unwanted side effects.

Greetings,
Thomas Mout

**Comment by ThomasMout** [comment]
Hi Thomas,

I've just implemented this feature and you can find it in the master branch. Hope it's what you're looking for!

Greetings,
Thomas Mout

**Comment by thomasvoorend** [comment]
Hi Thomas,

Thanks, this is also fine yes! :)

Kind regards,
Thomas Voorend

**Pull request merged**
