### PR TITLE
Added Recording and Streaming

### PR DESCRIPTION
**Pull request by agilbett**
Hi ThomasMout,

I think its a really neat little tally you created. I have added Recording and Streaming Tally and made it configurable in the web interface with a new dropdown menu.

Essentially this makes it easy to create on ON AIR light for a studio. Feel free to pull it in so other from the vMix forums can use this as well.

Andrew

### CODE REVIEW

**Comment by ThomasMout** [comment]
Hi Andrew,

Thanks for your contribution to this project. I like the idea for an ON AIR light for Recording and/or Streaming.

Unfortunately it looks like your additions changed the default functionality. The letters P and L will not be shown anymore when in Preview or Program state.
I hope you can find some time to take a look at this. 

Greetings,
Thomas

**Comment by agilbett** [comment]
Hi Thomas,

I have reverted back to default Preview/Live functionality. I have left the Dots and full Bitmaps in place as I might add another setting to use full red for live and the dots for preview, for easier viewing at a distance.

Let me know if that is suitable.

Andrew

**Comment by agilbett** [comment]
Hi Thomas,

I have added a drop down to select All LED's or Glyphs (Letters).

Andrew

**Comment by ThomasMout** [comment]
Hi Andrew,

I'm sorry for not responding.
I've decided not to add this feature to my repo. Feel free to use your own.

Thomas

**Pull request closed without merging**
